# Generated by Django 2.2.10 on 2020-03-06 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0017_auto_20191004_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='book_mark',
            field=models.ManyToManyField(blank=True, related_name='book_mark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='コメントを送信する場合は、Comments横のIcon(吹き出しマーク)をTapして下さい'),
        ),
    ]
