# Generated by Django 3.2.25 on 2025-06-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20250617_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, default='No-image.png', upload_to='article_pics', verbose_name='Photo'),
        ),
    ]
