# Generated by Django 3.2.25 on 2025-06-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_remove_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='No-image.png', upload_to='article_pics', verbose_name='Photo'),
        ),
    ]
