# Generated by Django 3.2.25 on 2025-06-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_article_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
    ]
