# Generated by Django 4.2.22 on 2025-07-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_delete_reel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='video',
            new_name='media',
        ),
    ]
