# Generated by Django 2.2.1 on 2019-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', help_text='著作権があるものはiconにはできません。', upload_to='profile_pics'),
        ),
    ]
