# Generated by Django 2.2.13 on 2020-07-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg',
            field=models.ImageField(blank=True, help_text='著作権を確認してください。', null=True, upload_to='user_background'),
        ),
    ]
