# Generated by Django 4.2.22 on 2025-07-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', help_text='著作権を確認してください。', upload_to='profile_pics'),
        ),
    ]
